### PR TITLE
riyazbagdadi adds san jose hometown file

### PR DESCRIPTION
**Pull request by riyazbagdadi**
This PR will add content for the San Jose , CA hometown file. :sunglasses: 

Some open :question:  before I merge

 1. If you havent been to SJ, what are you looking forward to?
 1. If you have been to SJ, what did you enjoy? what did you dislike?
 1. If you have small children, what activities do you enjoy doing with them?
 1. @angpaul2 when you visit other cities, do you like going yo theaters ?

### CODE REVIEW

**Comment by angpaul2** [comment]
@riyazbagdadi , whats good in SJ?

**Comment by githubteacher** [comment]
> what are you looking forward to?

I haven't been to San Jose, but being from the East coast I love the natural beauty of the West coast. Any recommendations for hiking or outdoor stuff? @riyazbagdadi

**Comment by riyazbagdadi** [comment]
@angpaul2 added some more info based on your feedback in commitid 546dfd8

**Comment by githubteacher** [comment]
👍 , 🚢  it, :shipit:

**Comment by angpaul2** [comment]
:+1:

**Comment by riyazbagdadi** [comment]
deleting branch

**Pull request merged**
